name: Upload Tools DL

on:
  workflow_dispatch:

jobs:
  makedlupload:
    name: Upload dl Files
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      run: |
        sudo git clone https://github.com/MATRIX06060/dl-download
        sudo cd dl-download
        ls


    - uses: actions/checkout@v2
    - name: Setup Debug Session
       uses: csexton/debugger-action@master

    - name: Upload Files
      uses: actions/upload-artifact@v2
      with:
        name: DLFILE
        path: dl/
