name: Upload Tools DL

on:
  workflow_dispatch:

jobs:
  makedlupload:
    name: Upload dl Files
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      run: |
        git clone https://github.com/openwrt/openwrt
        git clone https://github.com/MATRIX06060/dl-download

    - name: Config Move
      run: |
        mv dl-download/.config openwrt/.config
        cd openwrt

    - name: Get File
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make download -j8

    - name: Upload Files
      uses: actions/upload-artifact@v2
      with:
        name: DLFILE
        path: dl/
