name: Upload Tools DL

on:
  workflow_dispatch:

jobs:
  makedlupload:
    name: Upload dl Files
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      run: |
        git clone https://github.com/openwrt/openwrt
        git clone https://github.com/MATRIX06060/dl-download
        sudo apt update
        sudo apt upgrade
        sudo apt install -y binutils bzip2 diff find flex gawk gcc-6+ getopt grep install libc-dev libz-dev make4.1+ perl python3.7+ rsync subversion unzip which

    - name: Config Move
      run: |
        mv dl-download/.config openwrt/.config
        cd openwrt

    - name: Get File
      run: |
        make download -j8

    - name: Upload Files
      uses: actions/upload-artifact@v2
      with:
        name: DLFILE
        path: dl/
